### ISSUE TITLE
Cache no longer works

### ISSUE THREAD

**Issue by 16bravo** [16bravo/MatchOracle#71]
See why the cache is no longer working, resulting in longer execution times for the daily feed

**Comment by 16bravo** [comment]
OK by changing cache like this in the yaml file :
```
- name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: 'pip' 
```
